spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/users
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

